version: "3.8"
services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    restart: unless-stopped

  server:
    build: ../server
    env_file:
      - ../.env
    depends_on:
      - redis
    ports:
      - "4000:4000"
    restart: unless-stopped

  client:
    build: ../client
    ports:
      - "3000:80"
    restart: unless-stopped
